import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";
import { BlogsType, ProductType } from "../../components/types";

interface Props {
  blogs: BlogsType[];
}

const Blog: NextPage<Props> = ({ blogs }) => {
  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={"Blog"} />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                 { blogs.length > 0? 
                  blogs.map(blog =>  (
                    <BlogItem {...blog} key={blog.id} />)
                    ): <p>There are no results with your search.</p>}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form className="bor17 of-hidden pos-relative">
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    placeholder="Search"
                  />

                  <button className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4 className="mtext-112 cl2 p-b-33">Categories</h4>

                  <ul>
                    <li className="bor18">
                      <button className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
                        Fashion
                      </button>
                    </li>

                    <li className="bor18">
                      <button className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
                        Beauty
                      </button>
                    </li>

                    <li className="bor18">
                      <button className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
                        Street Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
                        Life Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
                        DIY & Crafts
                      </button>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Blog;

export const getStaticProps: GetStaticProps = async () => {
  const resBlogs = await fetch("http://localhost:5001/blogs");
  const blogs: ProductType[] = await resBlogs.json();

  return {
    props: {
      blogs,
    },
  };
};

// export const getServerSideProps: GetServerSideProps = async ({ query }) => {
//   const gender = query.gender;
//   const typeProd = query.q;

//   let link;
//   if (gender && typeProd) {
//     link = `http://localhost:5001/products?gender_like=${gender}&q=${typeProd}`;
//   } else if (gender) {
//     link = `http://localhost:5001/products?gender_like=${gender}`;
//   } else if (typeProd) {
//     link = `http://localhost:5001/products?q=${typeProd}`;
//   } else {
//     link = "http://localhost:5001/products";
//   }
//   console.log(link);
//   const resProducts = await fetch(link);
//   const productsData: ProductType[] = await resProducts.json();
//   return {
//     props: {
//       productsData,
//     },
//   };
// };