import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../../components/PageTitle";
import RelatedBlogs from "../../components/RelatedBlogs";
import { BlogsType, ProductType } from "../../components/types";

interface Props {
  blog: BlogsType;
  relatedBlogs: BlogsType[];
}
const BlogDetail: NextPage<Props> = ({ blog, relatedBlogs }) => {
  return (
    <>
      <Head>
        <title>Store - title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={blog.title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={blog.img} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">
                      {blog.category}
                    </span>

                    <span>
                      <span className="cl4">By</span> {blog.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>{blog.date}</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{blog.title}</h4>

                  <p className="stext-117 cl6 p-b-26">{blog.first_content}</p>

                  <p className="stext-117 cl6 p-b-26">{blog.second_content}</p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs relatedBlogs={relatedBlogs} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const resBlogs = await fetch("https://data-api-coza-store.vercel.app/blogs");
  const blogs: BlogsType[] = await resBlogs.json();

  const paths = blogs.map((blog) => {
    return { params: { id: blog.id } };
  });

  return {
    paths: paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = params?.id;

  const resRelated = await fetch(
    "https://data-api-coza-store.vercel.app/blogs?_start=$%7BrandomNo%7D&_limit=3"
  );
  const relatedBlogs: BlogsType[] = await resRelated.json();

  if (id) {
    const resBlog = await fetch(`https://data-api-coza-store.vercel.app/blogs/${id}`);
    const blog: BlogsType = await resBlog.json();
    return {
      props: { blog, relatedBlogs },
    };
  }

  return {
    notFound: true,
  };
};

export default BlogDetail;
